server:
  port: 9999
datasource:
  driverName: mysql
  hostname: 127.0.0.1
  port: 3306
  database: ASKPER
  username: root
  password: root
  charset: utf8
emailCode:
  smtpPassword: "样例邮箱码"
  email: "你的邮箱"
